version: "3.7"

services:

  home-back:
    container_name: home-back
    image: gelugu/home-db:1.0.0
    environment:
      DB_URL: home-postgres
      DB_NAME: home-postgres-db
      DB_PORT: "5432"
      DB_USER: home-postgres-user
      DB_PASSWORD: pass
    ports:
      - "8080:8080"
    networks:
      - home
    restart: unless-stopped

  home-postgres:
    container_name: home-postgres
    image: postgres:14.4-alpine
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: home-postgres-user
      POSTGRES_DB: home-postgres-db
      PGDATA: /data/postgres
    volumes:
      - ./.db-data/postgres:/data/postgres
      - ./cicd/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - home
    restart: unless-stopped

  pgadmin-home:
    container_name: pgadmin-home
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./.db-data/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - home
    restart: unless-stopped

networks:
  home:
    driver: bridge
