name: Build and push docker image

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run database
      run: docker-compose up home-postgres -d
    - name: Execute Gradle tests
      run: ./gradlew test
    - name: Stop database
      run: docker-compose down
    - name: Archive tests results
      uses: actions/upload-artifact@v3
      with:
        name: tests-report
        path: build/reports/tests/test/index.html
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file cicd/Dockerfile --tag gelugu/home-back:0.0.1
    - name: Docker login
      run: docker login -u gelugu -p ${{secrets.DOCKER_HUB_TOKEN}}
    - name: Push the Docker image
      run: docker push gelugu/home-back:0.0.1
