name: Test build and push docker image

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run database
      run: docker-compose up -d home-postgres
    - name: Execute Gradle tests
      run: ./gradlew test
    - name: Stop database
      run: docker-compose down

    - name: Archive tests results
      uses: actions/upload-artifact@v3
      with:
        name: tests-report
        path: build/reports/tests/test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run: docker login -u gelugu -p ${{secrets.DOCKER_HUB_TOKEN}}
    - name: Build the Docker image
      run: make docker-build
    - name: Push the Docker image
      run: make docker-push
